### ISSUE TITLE
Deprecate it in favor of ericpruitt/tmux.vim ?

### ISSUE THREAD

**Issue by blueyed** [keith/tmux.vim#14]
I've found that https://github.com/ericpruitt/tmux.vim is used by Vim/Neovim by default, and handles continuation in strings (similar to how it works in comments here already).

I think it is good to have a single source for this, and the other one appears to have scripting in place to update it automatically.

/cc @ericpruitt

**Comment by ericpruitt** [comment]
I think this issue is kind of ridiculous. Keith may not like the changes I've made. If he's happy with his version, he should continue to use it. Since my syntax file is now included with Vim by default, it's what most Vim users will ultimately end up using. The only reason they would have to Google "tmux syntax file for Vim" now would be if they don't like the default (mine), and in that case, they'll discover Keith's, and maybe they'll prefer it to mine.

**Comment by keith** [comment]
I'm going to archive this repo for yours / the default files with vim, which is what I'll start using.
